services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: plantravel5
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev -- --host 0.0.0.0